<?php
session_start();

require("feater.php");

$output = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">";
$output.= "<HTML>";
$output.= "<HEAD>";
$output.= 	"<META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"text/html; charset=utf-8\">";
$output.= 	"<TITLE></TITLE>";
$output.= 	"<META NAME=\"GENERATOR\" CONTENT=\"OpenOffice.org 2.4  (Linux)\">";
$output.= 	"<META NAME=\"AUTHOR\" CONTENT=\"Dan Meretzky\">";
$output.= 	"<META NAME=\"CREATED\" CONTENT=\"20090411;16021800\">";
$output.= 	"<META NAME=\"CHANGEDBY\" CONTENT=\"Dan Meretzky\">";
$output.= 	"<META NAME=\"CHANGED\" CONTENT=\"20090411;18234700\">";
$output.= 	"";
$output.= 	"<STYLE TYPE=\"text/css\">";
$output.= 	"<!--";
$output.= 		"@page { size: 8.5in 11in; margin: 0.79in }";
$output.= 		"P { margin-bottom: 0.08in }";
$output.= 		"H1 { margin-bottom: 0.08in }";
$output.= 		"H1.western { font-family: \"Nimbus Roman No9 L\", serif }";
$output.= 		"H1.cjk { font-family: \"DejaVu Sans\" }";
$output.= 		"H1.ctl { font-family: \"DejaVu Sans\" }";
$output.= 		"H2 { margin-bottom: 0.08in }";
$output.= 	"-->";
$output.= 	"</STYLE>";
$output.= "</HEAD>";
$output.= "<BODY LANG=\"en-US\" DIR=\"LTR\">";
$output.= "<H1 CLASS=\"western\">Terms of Service</H1>";
$output.= "<DIV ID=\"yt-static-main-content\" DIR=\"LTR\">";
$output.= 	"<H2>1. Your Acceptance</H2>";
$output.= 	"<OL>";
$output.= 		"<LI><P STYLE=\"margin-bottom: 0in\">By using and/or visiting this ";
$output.= 		"website you signify your agreement to these terms and conditions.</P>";
$output.= 		"<LI><P>This page contains the most up-to-date Terms of Service for";
$output.= 		"RPH.  You are responsible for adhering to all changes made to this ";
$output.= 		"document in the future.</P>";
$output.= 	"";
$output.= 	"</OL>";
$output.= 	"<H2>2. RPH Website</H2>";
$output.= 	"<OL>";
$output.= 		"<LI><P STYLE=\"margin-bottom: 0in\">These Terms of Service apply to ";
$output.= 		"all users of the RPH Website, including users who provide content ";
$output.= 		"to the Website.</P>";
$output.= 		"<LI><P STYLE=\"margin-bottom: 0in\">The RPH Website may contain links ";
$output.= 		"to third party websites.  These websites are not owned or ";
$output.= 		"controlled by RPH. RPH is relieved of all liability arising from ";
$output.= 		"your use of any third-party website, by your use of the Website.</P>";
$output.= 	"</OL>";
$output.= 	"<H2>3. Permissions and Restrictions</H2>";
$output.= 	"";
$output.= 	"<OL>";
$output.= 		"<LI><P STYLE=\"margin-bottom: 0in\">The content on the RPH Website is ";
$output.= 		"provided to you as is for your information and personal use only ";
$output.= 		"and may not be sold, licensed, or otherwise exploited for any other ";
$output.= 		"purposes whatsoever without the prior written consent of the ";
$output.= 		"respective owners.</P>";
$output.= 		"<LI><P STYLE=\"margin-bottom: 0in\">You may not upload any content to ";
$output.= 		"the Website that is not your personal work or that is copyrighted ";
$output.= 		"in someone else's name.</P>";
$output.=  	"</OL>";
$output.=  	"<H2>4. Account Termination Policy</H2>";
$output.=  	"<OL>";
$output.=  		"<LI><P STYLE=\"margin-bottom: 0in\">RPH will terminate a User's ";
$output.= 		"access to this Website if, under appropriate circumstances, they are ";
$output.= 		"determined to be a hazard to the Website."; 
$output.= 		"</P>";
$output.= 	"";
$output.= 		"<LI><P>RPH reserves the right to decide whether Projects or ";
$output.= 		"Comments are appropriate and comply with these Terms of Service. "; 
$output.= 		"Without prior notice, RPH may remove Projects and Comments and/or ";
$output.= 		"terminate a User's access.</P>";
$output.= 	"</OL>";
$output.= 	"<H2>5. Limitation of Liability</H2>";
$output.= 	"<P>	Use RPH at your own risk.  RPH is not liable for any ";
$output.= 	"offensive or harmful material 	that you may come in contact with ";
$output.= 	"while using the Website."; 
$output.= 	"</P>";
$output.= "</DIV>";
$output.= "</BODY>";
$output.= "</HTML>";

make_page ("About", $output);

?>

