<?php
session_start ();
require ("feater.php");

if ($_SESSION['username']== null)
{
  make_page ("Error", "<br />\n<center>\nYou must be logged in to access this page!\n</center>\n<br />");
  exit ();
}

$output = "<table width=\"500\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\n";
$output .= "<tr><td>\n";
$output .= "<form name=\"upload\" method=\"post\" action=\"uploadFiles.php\" enctype=\"multipart/form-data\">\n";
$output .= "<fieldset>\n";
$output .= "<legend><strong>Upload</strong></legend>\n";
$output .= "<table width=\"490\" border=\"0\" cellpadding=\"3\" cellspacing=\"1\" bgcolor=\"#FFFFFF\">\n";
$output .= "\n";
$output .= "<!-- Print Errors -->\n";
$output .= "\n";
$output .= "<!-- Project Name -->\n";
$output .= "<tr>\n";
$output .= "<td>Project Name</td>\n";
$output .= "<td>:</td>\n";
$output .= "<td><input name=\"projectName\" type=\"text\" id=\"projectName\" />\n";
$output .= "</td>\n";
$output .= "</tr>\n";
$output .= "\n";
$output .= "<!-- Name -->\n";
$output .= "<!--<tr>\n";
$output .= "<td>Project Author(s)</td>\n";
$output .= "<td>:</td>\n";
$output .= "<td><input type=text name=\"projectAuthor\" size=\"20\" /></td>\n";
$output .= "</tr>!-->\n";
$output .= "\n";
$output .= "<!-- Description -->\n";
$output .= "<tr>\n";
$output .= "<td>Project Description</td>\n";
$output .= "<td>:</td>\n";
$output .= "<td><textarea name=\"projectDescription\" cols=\"35\" rows=\"4\" ></textarea></td>\n";
$output .= "</tr>\n";
$output .= "\n";
$output .= "<!-- Is It For A Class -->\n";
$output .= "<tr>\n";
$output .= "<td>Was this project created for a class?</td>\n";
$output .= "<td>:</td>\n";
$output .= "<td><input type=radio name=\"projectIsForClass\" value=\"yes\" checked/> yes\n";
$output .= "    <input type=radio name=\"projectIsForClass\" value=\"no\" /> no </td>\n";
$output .= "</tr>\n";
$output .= "\n";
$output .= "\n";
$output .= "<!-- Class Name -->\n";
$output .= "<tr>\n";
$output .= "<td>Class Name</td>\n";
$output .= "<td>:</td>\n";
$output .= "<td><input type=text name=\"projectClass\" size=\"20\" /></td>\n";
$output .= "</tr>\n";
$output .= "\n";
$output .= "<!-- Major -->\n";
$output .= "<tr>\n";
$output .= "<td>Related Major</td>\n";
$output .= "<td>:</td>\n";
$output .= "<td><input type=text name=\"projectMajor\" size=\"20\" /></td>\n";
$output .= "</tr>\n";
$output .= "\n";
$output .= "<!-- Upload File -->\n";
$output .= "<tr>\n";
$output .= "<td>Choose a file to upload</td>\n";
$output .= "<td>:</td>\n";
$output .= "<td><input name=\"file\" type=\"file\" /></td>\n";
$output .= "</tr>\n";
$output .= "\n";
$output .= "<!-- Upload Picture -->\n";
$output .= "<!--<tr>\n";
$output .= "<td>Choose a picture to upload</td>\n";
$output .= "<td>:</td>\n";
$output .= "<td><input name=\"uploadedPic\" type=\"file\" /></td>\n";
$output .= "</tr>!-->\n";
$output .= "\n";
$output .= "<!-- Submit -->\n";
$output .= "<tr>\n";
$output .= "<td>&nbsp;</td>\n";
$output .= "<td>&nbsp;</td>\n";
$output .= "<td><input type=\"submit\" name=\"Submit\" value=\"Upload\" /></td>\n";
$output .= "</tr>\n";
$output .= "\n";
$output .= "<!-- Terms of Service -->\n";
$output .= "<tr>\n";
$output .= "<td colspan=\"3\">\n";
$output .= "<p style=\"font-size:12px\">By uploading files you certify that you have the right to distribute these files and that it does not violate the <a href=\"termsOfService.php\">Terms of Service</a>.</p>\n";
$output .= "</td>\n";
$output .= "</tr>\n";
$output .= "\n";
$output .= "</table>\n";
$output .= "</fieldset>\n";
$output .= "</form>\n";
$output .= "</td></tr>\n";
$output .= "</table>\n";
$output .= "Note: Max file size is 1MB.\n";
$output .= "<br />\n";

make_page ("Upload", $output);
?>
